pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm test'
                }
            }
            post {
                always {
                    junit 'Assignments/Assignment_2/backend/junit.xml'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    script {
                        docker.build('norwang2026/be-todo:assignment2')
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
                        docker.image('norwang2026/be-todo:assignment2').push()
                    }
                }
            }
        }
    }
}