pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh 'npm test'
                }
            }
            post {
                always {
                    junit 'Assignments/Assignment_2/backend/junit.xml'
                }
            }
        }

                stage('Docker Build') {
            steps {
                dir('Assignments/Assignment_2/backend') {
                    sh '/Applications/Docker.app/Contents/Resources/bin/docker build -t norwang2026/be-todo:assignment2 .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh '/Applications/Docker.app/Contents/Resources/bin/docker push norwang2026/be-todo:assignment2'
            }
        }
}